// Generated by CoffeeScript 1.4.0
(function() {
  var $, eye;

  $ = jQuery;

  /* Create Eyeball
  */


  eye = function(parent) {
    var e, p;
    e = $("<div class='eye'>");
    p = $("<div class='pupil'>");
    return e.append(p).prependTo(parent);
  };

  $(function() {
    eye($("body"));
    return $(".eye").draggable().click(function(e) {
      var h, offsetX, offsetY, w;
      w = $(this).outerWidth();
      h = $(this).outerHeight();
      offsetX = 10 * e.offsetX / w;
      offsetY = 10 * e.offsetY / h;
      return $(this).children(".pupil").animate({
        "margin-left": offsetX,
        "margin-top": offsetY
      });
    }).dblclick(function(e) {
      return $(this).css("background-color", "red");
    });
  });

}).call(this);
