// Generated by CoffeeScript 1.4.0
(function() {

  console.log("test");

  chrome.browserAction.onClicked.addListener(function(tab) {
    console.log("button pushed");
    chrome.tabs.insertCSS(null, {
      file: "css/googly.css"
    });
    chrome.tabs.executeScript(null, {
      file: "js/inject.js"
    });
    return console.log("after execute script");
  });

}).call(this);
