// Generated by CoffeeScript 1.4.0
(function() {

  chrome.browserAction.onClicked.addListener(function(tab) {
    chrome.tabs.insertCSS(null, {
      file: "css/googly.css"
    });
    return chrome.tabs.executeScript(null, {
      file: "js/inject.js"
    });
  });

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    var key, save_input;
    if (request.task === "save") {
      save_input = {};
      save_input[sender.tab.url] = request.data;
      console.log("Save request from " + sender.tab.url);
      chrome.storage.local.set(save_input, function() {
        sendResponse({
          status: "success"
        });
        return true;
      });
    }
    if (request.task === "load") {
      key = sender.tab.url;
      console.log("Load request from " + key);
      chrome.storage.local.get(key, function(data) {
        var resp;
        resp = data[key];
        console.log('Loading...');
        sendResponse({
          status: "success",
          data: resp
        });
        return true;
      });
    }
    return true;
  });

}).call(this);
